services:
  lox24.api.client_config:
    class: lox24\api_client\Config
    arguments:
      $token: '%lox24.api.token%'

  lox24.api.client_http:
    class: lox24\api_client\Client
    arguments:
      $config: '@lox24.api.client_config'
      $requestFactory: '%lox24.api.request_factory%'
      $httpClient: '%lox24.api.http_client%'

  lox24\api_client\api\Lox24Api:
    arguments:
      $client: '@lox24.api.client_http'
